name: Update guides/hack from facebook/hhvm repo

on:
  push:
    branches:
      # Run when changes are pushed to main too. This makes it easier
      # to make changes to this file and see the results.
      - main
  schedule:
    # Fifteen minutes past the hour, every hour.
    # (GitHub actions are heavily used at o'clock, so arbitrarily
    # choose another time.)
    - cron: '15 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout user-documentation
        uses: actions/checkout@v3

      - name: Download the latest facebook/hhvm
        run: wget https://github.com/facebook/hhvm/archive/refs/heads/master.zip

      - name: Unzip
        run: unzip -q master.zip

      - name: Check directory contents
        run: ls

      - name: Remove old copy of Hack guides
        run: rm -r guides/hack

      - name: Use the latest copy of the manual from facebook/hhvm instead
        run: cp -r hhvm-master/hphp/hack/manual/hack guides

      - name: Clean up
        run: rm -r hhvm-master master.zip

      - name: Create a commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update guides/hack from HHVM repostory
